import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    testTimeout: 30_000,
    hookTimeout: 30_000,
    include: ['tests/**/*.test.{ts,tsx}'],
    exclude: [
      'tests/browser/**',
      'tests/accessibility/**',
      'tests/worker/**',
      'tests/live-browser/**',
    ],
    reporters: ['default'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'html', 'lcov'],
      reportsDirectory: 'coverage',
      include: [
        'src/core/**/*.ts',
        'src/adapters/**/*.ts',
        'src/profiles/**/*.ts',
        'src/faults/**/*.ts',
        'src/verification/**/*.ts',
        'src/export/**/*.ts',
        'src/campaign/**/*.ts',
        'src/investigation/**/*.ts',
        'src/ml/temporalModel.ts',
        'src/model-registry/**/*.ts',
        'src/temporal/**/*.ts',
        'src/live/**/*.ts',
        'src/operations/**/*.ts',
        'src/map/**/*.ts',
        'src/replay/**/*.ts',
        'src/evidence/**/*.ts',
        'src/features/live/**/*.{ts,tsx}',
        'src/features/lab/**/*.{ts,tsx}',
        'src/features/replay/**/*.{ts,tsx}',
        'src/features/evidence/**/*.{ts,tsx}',
        'src/features/workbench/**/*.{ts,tsx}',
        'src/ui/charts.ts',
      ],
      exclude: ['**/*.d.ts', '**/index.ts', '**/types.ts', 'src/campaign/browserClient.ts'],
      thresholds: {
        branches: 90,
        functions: 90,
        lines: 90,
        statements: 90,
      },
    },
  },
});
